<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class OrderItemRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        switch ($this->method()) {
            case 'POST':
                return [
                    'name' => 'required|min:2|max:30',
                    'price' => 'required|min:0',
                    'amount' => 'required|between:1,9999',
                    'product_id' => 'required|exists:product,id',
                    'order_id' => 'required|exists:gross_order,id'
                ];
            case 'PUT':
                return [
                    'name' => 'min:2|max:3',
                    'price' => 'min:0',
                    'amount' => 'between:1,9999',
                    'product_id' => 'exists:product,id',
                    'order_id' => 'exists:orders,id'
                ];
        }
    }

    public function  messages()
    {
        return [
            'amount.between'=>'数量必须大于1小于9999',
            'product_id.exists'=>'仓库产品不存在此pid',
            'order_id.exists'=>'订单id不存在'
        ]; // TODO: Change the autogenerated stub
    }
}
